### PR TITLE
changes

### PR DESCRIPTION
**Pull request by adeelq**

### CODE REVIEW

**Comment by cdiacon** [comment]
@adeelq Log viewer change : 

If any file is empty the error is shown.

**Comment by cdiacon** [comment]
@adeelq Log  viewer change : 

May be a good idea to exclude from dropdrown system files(system/exception) if the Log Settings from admin is set to NO

**Comment by cdiacon** [comment]
@adeelq so these changes will hold the preview window on top of the group window on fixed position https://github.com/dotmailer/dotmailer-magento-extension/pull/175/commits/c1b1705eedaed4688d06c23a13b79462357e3123#diff-97ad195f8dbceb26e583302f337161b5L38 ?!?

**Comment by adeelq** [comment]
@cdiacon correct

**Comment by cdiacon** [comment]
why is that was working fine before the last commit?

**Comment by adeelq** [comment]
because of unpredictable result. Sometimes work and sometimes it does not. I tried playing around and thought best to gave a fix position for it.

**Comment by cdiacon** [comment]
@adeelq so this is still an issue https://github.com/dotmailer/dotmailer-magento-extension/pull/175#issuecomment-273813452

```
<pre>Warning: fread(): Length parameter must be greater than 0  in /.modman/dotmailer-magento-extension/code/Dotdigitalgroup/Email/Helper/Data.php on line 1012
```

**Comment by adeelq** [comment]
@cdiacon I found this issue on M2 when i wrote the test. I can apply the same fix.

**Comment by cdiacon** [comment]
@adeelq Log viewer - we don't need the button would be better to just ajax call for every 10sec so you'll active updates of the file instead of clicking the button all the time.

**Comment by cdiacon** [comment]
@adeelq Log viewer the active log settings must be for website level https://github.com/dotmailer/dotmailer-magento-extension/blob/70edc7bbe6eb6b685e7568b2d46df3e852633b7b/design/adminhtml/default/default/template/connector/dashboard/logs.phtml#L5-L5

**Comment by cdiacon** [comment]
@adeelq actually you can remove the config check and display all the options because it looks like a bug if you get different options in dropdown, and display only the file content only if it's enabled
https://github.com/dotmailer/dotmailer-magento-extension/blob/70edc7bbe6eb6b685e7568b2d46df3e852633b7b/design/adminhtml/default/default/template/connector/dashboard/logs.phtml#L5-L5

**Comment by cdiacon** [comment]
Historical data refresh : 

* shorten the url params "to" and "from"
* move the date selector above the transactional data sync excluding the Contacts and Subscribers
* comment for date selector : 

```
IMPORTANT - No need to save config to use date range values! If any of the data range is not selected then full data refresh will be done. This Date Range does not apply on Customer and Subscribers.
```

**Comment by cdiacon** [comment]
@adeelq you forgot about to remove the button https://github.com/dotmailer/dotmailer-magento-extension/pull/175/files/a6e9bb01227da2958a2ad8d01bd7b66bffbaf2e1..0d24415f1cc31dccf6e0568850996fd00dc91ba7

**Comment by cdiacon** [comment]
@adeelq now the ajax loader is annoing on other dashboard tabs

**Comment by cdiacon** [comment]
@adeelq Historical Order  : 

Using the "updated_at" field for historical sync is wrong when you have already run the sync(and more) the updated_at will all have the same time at some point which makes HS = Sync all

replace "updated_at" with "created_at" for all transactional data reset.

**Pull request merged**
