### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by adeelq**

### CODE REVIEW

**Comment by cdiacon** [comment]
@adeelq not sure about the campaign statuses, shouldn't they match these statuses instead : 

https://apiconnector.com/v2/help/wadl#ApiCampaignStatuses

and use only the FAILED if the campaign is not set up properly?

**Comment by adeelq** [comment]
@cdiacon Advise was to to follow statuses like importer so i did exactly like importer. 
Pending - Not started yet
Processing - Sent but status not confirmed 
Sent - Sent from magento and dotmailer
Failed - Failed to send and reason will be given

**Comment by cdiacon** [comment]
@adeelq only FALED is matching the one from importer.

PENDING is never used.

**Comment by adeelq** [comment]
@cdiacon Pending is Not Imported in Importer

**Pull request merged**
